version: '3'
services:
  api:
    build: .
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:80"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"


